### ISSUE TITLE
Mod Breaks After Relog

### ISSUE THREAD

**Issue by VoidIsNoLongerHere** [ploppyperson/AutoTorch#1]
The inventory opens after using /at however not torches are placed and when the gui is closed it gives the error

Further investigation proved that the error is thrown when any inventory is closed

`[Server thread/ERROR]: Could not pass event InventoryCloseEvent to AutoTorch2 v2.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1379) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2629) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:15) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:6) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3566-Spigot-584b459-c379a6b]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.event.inventory.InventoryCloseEvent$Reason org.bukkit.event.inventory.InventoryCloseEvent.getReason()'
        at uk.antiperson.autotorch.gui.GuiListeners.onClose(GuiListeners.java:51) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more`

**Comment by VoidIsNoLongerHere** [comment]
Modlist: FreedomChat, LuckPerms, WorldEdit, UberEnchant, Essentials, Not-Too-Expensive, AutoTorch2, Multiverse-Core, Multiverse-Inventories, Multiverse-SignPortals, Multiverse-Portals, CommandSigns, Multiverse-NetherPortals

**Comment by ploppyperson** [comment]
Fixed in 2.0.1
